### ISSUE TITLE
reflects changes respect the original plugin

### ISSUE THREAD

**Issue by mckaygerhard** [dsoares/rcguard-old#10]
the changes are restricted to a small note at the end of the README.md

please added a more detailed changed that reflects target of this fork!

**Comment by dsoares** [comment]
This is an open source project. The changes made by me and other contributors to this project can be consulted on the repository log.  The original author is explicit in the `README`, `composer.json` and in the main script `rcguard.php`.

**Comment by dsoares** [comment]
This issue was moved to dsoares/rcguard#10
