### ISSUE TITLE
Provide the ability to disable IP sending

### ISSUE THREAD

**Issue by udf2457** [dsoares/rcguard-old#21]
The sending of the user's IP address to Google is optional.  Please provide a way to disable this.

**Comment by dsoares** [comment]
Hi,
Yes, i will do that ASAP.

**Comment by dsoares** [comment]
Done in release [1.0.9](https://github.com/dsoares/rcguard/releases/tag/1.0.9). Thank you.

**Comment by dsoares** [comment]
This issue was moved to dsoares/rcguard#21
