### ISSUE TITLE
Recaptcha not show

### ISSUE THREAD

**Issue by andrkaz** [dsoares/rcguard-old#22]
After incorrect logins I see message "CAPTCHA verification empty!" but dont see captcha. Also dont working release IP after expire time.
My software:
Sqlite 3-3.22.0
Rcguard version 1.0.10
Roundcube 1.3.4

**Comment by ghost** [comment]
Try to force https by setting 
`$rcmail_config['recaptcha_https'] = true;`
in your config/config.inc.php file.

Solved the issue for me. The plugin uses `$_SERVER['HTTPS']` to decide wether to use http or https to display reCAPTCHA. If your roundcube installation is on an http server and your site is running behind a revers proxy that does https your browser may not display mixed content correctly.

https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox

**Comment by andrkaz** [comment]
To Imshao.
I trying, nothing happens...

**Comment by dsoares** [comment]
Please use your browser console to check for errors (Javascript or Network errors).

**Comment by dsoares** [comment]
@Imshao thank you for pointing out that `$_SERVER['HTTPS']` usage. 
I released a new version using the better `rcube_utils::https_check()`.

**Comment by andrkaz** [comment]
No errors in console, but captcha dont show. I enable error log, in log only authorisation errors.
Update: trying Larry and Classic skins

**Comment by dsoares** [comment]
Did you check the Network tab on the Console? All resources are loaded?
What's your plugin configuration?

**Comment by andrkaz** [comment]
I install Rcguard by command "php composer.phar install" after adding rcguard in composer.json. Then register domain in Google and write public and private keys in config.inc.php. I write email to you with my domain, because I dont know what see in console tabs.

**Comment by dsoares** [comment]
This issue was moved to dsoares/rcguard#22
