### ISSUE TITLE
postgres status

### ISSUE THREAD

**Issue by mckaygerhard** [dsoares/rcguard-old#9]
noted too many mysql like commits..

what are the status of postgresql?!

**Comment by dsoares** [comment]
I don't understand why you say "many mysql like commits". Care to explain and give some commit id examples of "mysql like commits"?
The plugin works with postgresql.

**Comment by mckaygerhard** [comment]
arrggg i posted in wrong place, i mean in the lastlogin.. going to that project.. sorry

**Comment by dsoares** [comment]
This issue was moved to dsoares/rcguard#9
